{
	"id": "oval:org.opensuse.security:def:202341164",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2023-41164",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2023-41164",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41164",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2023-41164",
				"ref_url": "https://www.suse.com/security/cve/CVE-2023-41164",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2023:3533-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-updates/2023-September/031348.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2023:3580-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-September/016133.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2023-41164 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2023-41164/",
					"impact": "medium",
					"cvss3": "6.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L"
				},
				{
					"text": "CVE-2023-41164 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2023-41164",
					"impact": "high",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1214667",
					"href": "https://bugzilla.suse.com/1214667"
				}
			],
			"issued": {
				"date": "2023-09-07"
			},
			"updated": {
				"date": "2024-09-01"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009932501",
						"comment": "python310-Django-4.2.5-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939568",
						"comment": "python310-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009932502",
						"comment": "python311-Django-4.2.5-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939569",
						"comment": "python311-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939570",
						"comment": "python312-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009932503",
						"comment": "python39-Django-4.2.5-1.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
