{
	"id": "oval:org.opensuse.security:def:202132052",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2021-32052",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2021-32052",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32052",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2021-32052",
				"ref_url": "https://www.suse.com/security/cve/CVE-2021-32052",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "openSUSE-SU-2023:0005-1",
				"ref_url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/UHF5IZKTZ2T4T4QQYZMUFHW422X3WCU6/",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2021-32052 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2021-32052/",
					"impact": "medium",
					"cvss3": "5.4/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N"
				},
				{
					"text": "CVE-2021-32052 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2021-32052",
					"impact": "medium",
					"cvss3": "6.1/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1185713",
					"href": "https://bugzilla.suse.com/1185713"
				}
			],
			"issued": {
				"date": "2021-10-02"
			},
			"updated": {
				"date": "2024-09-01"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937554",
						"comment": "python310-Django-4.2.11-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939568",
						"comment": "python310-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937555",
						"comment": "python311-Django-4.2.11-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939569",
						"comment": "python311-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937556",
						"comment": "python312-Django-4.2.11-2.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009939570",
						"comment": "python312-Django4-4.2.14-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912572",
						"comment": "python36-Django-3.2.7-2.3 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912573",
						"comment": "python38-Django-3.2.7-2.3 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912574",
						"comment": "python39-Django-3.2.7-2.3 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
