{
	"id": "oval:org.opensuse.security:def:202121241",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2021-21241",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2021-21241",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-21241",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2021-21241",
				"ref_url": "https://www.suse.com/security/cve/CVE-2021-21241",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2022:3093-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-September/012106.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    The Python \"Flask-Security-Too\" package is used for adding security features to your Flask application. It is an is a independently maintained version of Flask-Security based on the 3.0.0 version of Flask-Security. In Flask-Security-Too from version 3.3.0 and before version 3.4.5, the /login and /change endpoints can return the authenticated user's authentication token in response to a GET request. Since GET requests aren't protected with a CSRF token, this could lead to a malicious 3rd party site acquiring the authentication token. Version 3.4.5 and version 4.0.0 are patched. As a workaround, if you aren't using authentication tokens - you can set the SECURITY_TOKEN_MAX_AGE to \"0\" (seconds) which should make the token unusable.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2021-21241 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2021-21241/",
					"impact": "high",
					"cvss3": "7.4/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N"
				},
				{
					"text": "CVE-2021-21241 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2021-21241",
					"impact": "high",
					"cvss3": "7.4/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1181058",
					"href": "https://bugzilla.suse.com/1181058"
				}
			],
			"issued": {
				"date": "2024-01-07"
			},
			"updated": {
				"date": "2024-09-01"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009935450",
						"comment": "python310-Flask-Security-Too-5.3.2-3.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009935451",
						"comment": "python311-Flask-Security-Too-5.3.2-3.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009935452",
						"comment": "python39-Flask-Security-Too-5.3.2-3.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
