{
	"id": "oval:org.opensuse.security:def:20220329",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2022-0329",
		"affected": {
			"family": "unix",
			"Platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2022-0329",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0329",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2022-0329",
				"ref_url": "https://www.suse.com/security/cve/CVE-2022-0329",
				"source": "SUSE CVE"
			}
		],
		"Description": "\n    ** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. Reason: This CVE has been rejected as it was incorrectly assigned. All references and descriptions in this candidate have been removed to prevent accidental usage.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Low",
			"cve": {
				"text": "CVE-2022-0329 at NVD",
				"href": "https://nvd.nist.gov/vuln/detail/CVE-2022-0329",
				"impact": "low"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 1195000",
					"href": "https://bugzilla.suse.com/1195000"
				}
			],
			"issued": {
				"date": "2022-08-13"
			},
			"updated": {
				"date": "2024-04-18"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009706587",
						"comment": "python310-loguru-0.6.0-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009706588",
						"comment": "python38-loguru-0.6.0-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009706589",
						"comment": "python39-loguru-0.6.0-1.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
