{
	"id": "oval:org.opensuse.security:def:20162513",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2016-2513",
		"affected": {
			"family": "unix",
			"Platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2016-2513",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2513",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2016-2513",
				"ref_url": "https://www.suse.com/security/cve/CVE-2016-2513",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "openSUSE-SU-2018:0824-1",
				"ref_url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00103.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "openSUSE-SU-2018:0826-1",
				"ref_url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00105.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    The password hasher in contrib/auth/hashers.py in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack involving login requests.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Low",
			"cve": {
				"text": "CVE-2016-2513",
				"href": "https://www.suse.com/security/cve/CVE-2016-2513/",
				"impact": "low",
				"cvss3": "3.1/CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 968000",
					"href": "https://bugzilla.suse.com/968000"
				}
			],
			"issued": {
				"date": "2021-10-02"
			},
			"updated": {
				"date": "2023-07-01"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009642302",
				"comment": "python3-Django-1.10.4-1.1 is installed"
			}
		]
	}
}
